### ISSUE TITLE
Not working on Apple Silicon macs

### ISSUE THREAD

**Issue by Kakise** [Chris911/iStats#101]
While the install works perfectly fine on Apple Silicon, I have the following error when trying to run the gem:

(base)  ~/ /usr/local/bin/istats
Traceback (most recent call last):
	7: from /usr/local/bin/istats:23:in `<main>'
	6: from /usr/local/bin/istats:23:in `load'
	5: from /Library/Ruby/Gems/2.6.0/gems/iStats-1.6.1/bin/istats:6:in `<top (required)>'
	4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	2: from /Library/Ruby/Gems/2.6.0/gems/iStats-1.6.1/lib/iStats.rb:2:in `<top (required)>'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Library/Ruby/Gems/2.6.0/gems/iStats-1.6.1/lib/osx_stats.bundle, 0x0009): missing compatible arch in /Library/Ruby/Gems/2.6.0/gems/iStats-1.6.1/lib/osx_stats.bundle - /Library/Ruby/Gems/2.6.0/gems/iStats-1.6.1/lib/osx_stats.bundle (LoadError)

**Comment by snorkrat** [comment]
Just adding I have the exact same issue on a new 2020 Mac Mini with Apple M1

**Comment by darrenlin** [comment]
I am also using a M1 MacBook. Install Ruby3 using brew in x86 mode and use the gem installer in x86 mode worked for me. I am able to run it using the newer version of ruby3. However the information displayed is not 100% correct. See below: 

```
➜  ~ iStats
--- CPU Stats ---
CPU temp:               0.0°C       ▁▂▃▅▆▇

--- Fan Stats ---
Total fans in system:   0           

--- Battery Stats ---
Battery health:         Check Battery
Cycle count:            1           ▁▂▃▅▆▇  0.1%
Max cycles:             1000        
Current charge:         70 mAh      ▁▂▃▅▆▇  70%
Maximum charge:         100 mAh     ▁▂▃▅▆▇  2.3%
Design capacity:        4382 mAh    
Battery temp:           0.0°C       

```

**Comment by Kakise** [comment]
> I am also using a M1 MacBook. Install Ruby3 using brew in x86 mode and use the gem installer in x86 mode worked for me. I am able to run it using the newer version of ruby3. However the information displayed is not 100% correct. See below:
> 
> ```
> ➜  ~ iStats
> --- CPU Stats ---
> CPU temp:               0.0°C       ▁▂▃▅▆▇
> 
> --- Fan Stats ---
> Total fans in system:   0           
> 
> --- Battery Stats ---
> Battery health:         Check Battery
> Cycle count:            1           ▁▂▃▅▆▇  0.1%
> Max cycles:             1000        
> Current charge:         70 mAh      ▁▂▃▅▆▇  70%
> Maximum charge:         100 mAh     ▁▂▃▅▆▇  2.3%
> Design capacity:        4382 mAh    
> Battery temp:           0.0°C       
> ```

I have the same behavior when following your steps on the M1 MBP

**Comment by Casuallynoted** [comment]
Having the same issues here. Currently getting "missing compatible arch in /Library/Ruby/Gems/2.6.0/gems/iStats-1.6.1/lib/osx_stats.bundle"

**Comment by snorkrat** [comment]
Just wondering if there are any plans to look at this and make it compatible with Apple Silicon?

**Comment by RamiAlzayat** [comment]
Same here :(

**Comment by matthutchinson** [comment]
+1 me too

**Comment by shouryasaha** [comment]
I am having the same issue of incorrect stats displaying, viz CPU temp 0.

```
░▒▓    ~  istats all                                                                                            ✔  at 09:16:06 PM  ▓▒░
--- CPU Stats ---
CPU temp:               0.0°C       ▁▂▃▅▆▇

--- Fan Stats ---
Total fans in system:   2
Fan 0 speed:            0 RPM       ▁▂▃▅▆▇
Fan 1 speed:            0 RPM       ▁▂▃▅▆▇

--- Battery Stats ---
Battery health:         Check Battery
Cycle count:            19          ▁▂▃▅▆▇  1.9%
Max cycles:             1000
Current charge:      64 mAh      ▁▂▃▅▆▇  64%
Maximum charge    100 mAh     ▁▂▃▅▆▇  1.2%
Design capacity:     8694 mAh
Battery temp:          0.0°C
```

**Comment by Artoria2e5** [comment]
Expecting the Rosetta fake-sensor to work at all is futile. The only way here is to actually do native M1 support.

Incidentially, this issue is the only one that pastes the failed output! The paste isn't perfect (use a code block next time), but it's readable enough.

**Comment by Artoria2e5** [comment]
Huh, this is interesting. The `extconf.rb` part says nothing about a hard-coded arch. Anyone care to upload a zipped copy of `/Library/Ruby/Gems/2.6.0/gems/iStats-1.6.1/lib/osx_stats.bundle`?

**Comment by PeterDaveHello** [comment]
The last commit of this project is almost five years ago, there are some pull requests will need @Chris911 to take a look first, so maybe someone who's interesting in helping iStats to work on Apple Silicon can send the patches here.
